### ISSUE TITLE
Doesn't support iOS

### ISSUE THREAD

**Issue by BrianGeppert** [google/mathfu#4]
Is iOS support planned?  If not, would you accept a PR adding iOS support?

**Comment by stewartmiles** [comment]
We're happy to take PRs for iOS support.  I would love to see what you mean
in particular.  Is this just a project change, are there issues with some
of vectorial's intrinsics?  If it's changes to vectorial (
https://github.com/scoopr/vectorial) then it's probably better to send the
PR over there and we'll merge the change.  If it's Xcode projects for iOS,
it would be great to know what you're thinking since there are potentially
a lot of built targets that need to be maintained for all of our test cases.

Cheers,
Stewart

**Comment by BrianGeppert** [comment]
Honestly, I'm not sure what I mean.  I just saw that iOS wasn't on the list
of supported platforms.  I'm not supporting iOS yet, so I haven't had a
chance to figure out what's needed (if anything).

Cheers,
Brian

**Comment by stewartmiles** [comment]
MathFu is a header only library.  Our tests only run on desktop platforms
and Android purely because we don't have build files for iOS.  Try pulling
the headers into a project .. I'm *fairly* sure it will work ;)

**Comment by BrianGeppert** [comment]
Oh, awesome.  Thanks!
